'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { FormEvent, useMemo, useState } from 'react';
import type { SiteRoute } from '@/lib/site-routes';
import { memberNavigation } from '@/lib/site-routes';

const nav = [['Home','/'],['Church','/church'],['Mission','/mission'],['KCA','/kca'],['Press','/press'],['Events','/events'],['Give','/give']] as const;
const sampleRows = [
  ['Grace Family House', 'Lagos, Nigeria', 'Active'], ['Kingdom Advancement', 'May 30, 2024', 'In Progress'], ['Sunday Celebration', '10:00 AM', 'Upcoming'], ['Samuel David', 'Member since 2023', 'Verified'],
];

function Logo() { return <Link className="site-logo" href="/"><span>⬡</span><b>FAMILY HOUSE<br/>CONNECT</b></Link>; }
function Header() { const pathname = usePathname(); return <header className="site-header"><Logo/><nav>{nav.map(([label,href])=><Link className={pathname===href?'active':''} href={href} key={href}>{label}</Link>)}</nav><div className="header-actions"><Link href="/search" aria-label="Search">⌕</Link><Link className="avatar" href="/account">JD</Link><Link className="site-button small" href="/login">Sign In</Link></div></header>; }
function Sidebar() { const pathname=usePathname(); return <aside className="member-sidebar"><div className="member-person"><span className="avatar big">JD</span><div><b>John Doe</b><small>View Profile</small></div></div>{memberNavigation.map(([href,label])=><Link className={pathname===href?'active':''} href={href} key={href}><span>◈</span>{label}</Link>)}<Link className="logout" href="/login">↪ Logout</Link></aside>; }
function Progress({route}:{route:SiteRoute}) { if(route.surface!=='workflow') return null; const steps=['Personal','Church Info','Walk with Christ','Details','Review','Submit']; const index=Math.max(1,Math.min(5, route.path.split('/').length-2)); return <div className="workflow-progress">{steps.map((s,i)=><div className={i<=index?'done':''} key={s}><span>{i<index?'✓':i+1}</span><small>{s}</small></div>)}</div>; }

function Hero({route}:{route:SiteRoute}) { return <section className={`site-hero hero-${route.section.toLowerCase()}`}><div><span className="eyebrow">FAMILY HOUSE CONNECT</span><h1>{route.title}</h1><p>{route.subtitle} We are one family, growing in faith and making a lasting impact.</p><div className="hero-actions"><Link className="site-button" href={route.section==='KCA'?'/kca/enrol':route.section==='Mission'?'/mission/impact':route.section==='Church'?'/find-church':'/about'}>{route.action??'Learn More'}</Link><Link className="site-button secondary" href="/contact">Learn More</Link></div></div><div className="hero-art"><span>✦</span><b>{route.section}</b><small>Faith · Family · Purpose</small></div></section>; }
function Metrics(){return <div className="metric-grid">{[['50,000+','Lives Impacted'],['1,842','Active Churches'],['147','Countries'],['2M+','Members']].map(([v,l])=><article key={l}><strong>{v}</strong><span>{l}</span><em>+12.4%</em></article>)}</div>}
function Cards({route}:{route:SiteRoute}) { const labels=route.section==='KCA'?['Biblical Training','Practical Ministry','Kingdom Impact','Global Network']:route.section==='Mission'?['Evangelism','Discipleship','Humanitarian Aid','Church Planting']:['Find a Church','Grow & Serve','Join a Community','Make an Impact']; return <section className="site-cards">{labels.map((label,i)=><article key={label}><span className="card-icon">{['✦','♢','◉','⌁'][i]}</span><h3>{label}</h3><p>Connect with people, resources, and opportunities designed for your journey.</p><Link href={route.section==='KCA'?'/kca/why':route.section==='Mission'?'/mission/impact':'/church'}>Explore →</Link></article>)}</section> }
function Listing({route}:{route:SiteRoute}) { return <><div className="toolbar"><input aria-label="Search" placeholder={`Search ${route.section.toLowerCase()}...`}/><select aria-label="Filter"><option>All Categories</option><option>Active</option></select><button className="site-button">Filter</button></div><div className="content-grid"><section className="panel table-panel">{sampleRows.concat(sampleRows).map((row,i)=><Link href={route.section==='Events'?'/events/kingdom-advancement-conference-2024':route.section==='Mission'?'/mission/partners/loveworld-outreach':'/account'} className="list-row" key={i}><span className="thumb">{route.section[0]}</span><div><b>{row[0]}</b><small>{row[1]}</small></div><span className="status">{row[2]}</span><button>View</button></Link>)}</section><aside className="panel side-card"><h3>Featured</h3><div className="mini-art">✦</div><b>Kingdom Advancement</b><p>Discover what God is doing through our global family.</p><button className="site-button">View Details</button></aside></div></> }
function FormScreen({route}:{route:SiteRoute}) { const router=useRouter(); const [done,setDone]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setDone(true);setTimeout(()=>{ if(route.path.includes('/start-home-church/apply/')) router.push('/start-home-church/apply/review'); },500)}; return <form className="site-form" onSubmit={submit}><div className="form-grid"><label>Full Name<input required defaultValue="John Chinedu Doe"/></label><label>Email Address<input type="email" required defaultValue="john.doe@email.com"/></label><label>Phone Number<input defaultValue="+234 801 234 5678"/></label><label>Location<select><option>Lagos, Nigeria</option><option>Abuja, Nigeria</option></select></label><label>Category<select><option>Select an option</option><option>Church</option><option>Mission</option></select></label><label>Date<input type="date" defaultValue="2024-05-31"/></label><label className="wide">Tell us more<textarea defaultValue="I would like to take the next step in my Kingdom journey."/></label></div><div className="choice-grid">{['I agree to the commitment','Keep me informed','Use my current information'].map(x=><label key={x}><input type="checkbox" defaultChecked/> {x}</label>)}</div><div className="form-actions"><button type="button" className="site-button secondary" onClick={()=>router.back()}>Back</button><button className="site-button">{done?'Saved ✓':route.action??'Save & Continue'}</button></div></form> }
function Dashboard({route}:{route:SiteRoute}) { return <><div className="welcome"><div><span className="eyebrow">MY FAMILY HOUSE</span><h2>{route.title}</h2><p>{route.subtitle}</p></div><button className="site-button">{route.action??'View Calendar'}</button></div><Metrics/><div className="dashboard-grid"><section className="panel"><h3>Upcoming & Recent</h3>{sampleRows.map((r,i)=><div className="activity" key={i}><span>{i+1}</span><div><b>{r[0]}</b><small>{r[1]}</small></div><em>{r[2]}</em></div>)}</section><section className="panel"><h3>Your Progress</h3>{['Faith Journey','Ministry Training','Community','Giving'].map((x,i)=><div className="progress-row" key={x}><span>{x}</span><div><i style={{width:`${82-i*12}%`}}/></div><b>{82-i*12}%</b></div>)}</section></div></> }
function Settings({route}:{route:SiteRoute}) { const [saved,setSaved]=useState(false); return <div className="settings-panel"><section className="panel"><h3>{route.title}</h3><p>Manage your personal information, preferences, and account security.</p>{['Email notifications','SMS notifications','Login alerts','Church announcements','Event reminders'].map((x,i)=><label className="setting-row" key={x}><span><b>{x}</b><small>Keep your account and journey up to date.</small></span><input type="checkbox" defaultChecked={i<4}/></label>)}<button className="site-button" onClick={()=>setSaved(true)}>{saved?'Changes Saved ✓':route.action??'Save Changes'}</button></section><aside className="panel profile-card"><span className="avatar huge">JD</span><h3>John Chinedu Doe</h3><p>Member · Lagos, Nigeria</p><span className="status">Verified</span></aside></div> }
function Media({route}:{route:SiteRoute}) { return <><div className="media-stage"><div className="play">▶</div><div><span className="live">● LIVE</span><h2>{route.title}</h2><p>Join the Family House Connect global family live and on demand.</p></div></div><div className="media-tabs"><button>Overview</button><button>Schedule</button><button>Sermons</button><button>Bible Study</button></div><Cards route={route}/></> }
function Document({route}:{route:SiteRoute}) { return <div className="document-wrap"><div className="document"><span>⬡</span><h5>FAMILY HOUSE CONNECT</h5><h2>{route.title}</h2><p>This is to certify that</p><h1>John Chinedu Doe</h1><p>has successfully completed the required programme and is in good standing.</p><div className="signatures"><i>Pastor Daniel David</i><i>May 31, 2024</i></div></div><button className="site-button">{route.action}</button></div> }

export function SiteScreen({route}:{route:SiteRoute}) { const isMember=route.surface==='member'; const content=useMemo(()=>{if(route.kind==='landing')return <><Hero route={route}/><Metrics/><Cards route={route}/></>;if(route.kind==='listing'||route.kind==='detail'||route.kind==='map')return <Listing route={route}/>;if(route.kind==='form')return <FormScreen route={route}/>;if(route.kind==='success')return <div className="success-card"><span>✓</span><h1>{route.title}</h1><p>{route.subtitle}</p><Link className="site-button" href="/account">{route.action}</Link></div>;if(route.kind==='dashboard')return <Dashboard route={route}/>;if(route.kind==='settings')return <Settings route={route}/>;if(route.kind==='media')return <Media route={route}/>;return <Document route={route}/>},[route]); return <div className={`site-app surface-${route.surface}`}><Header/><Progress route={route}/><div className={isMember?'member-layout':'site-layout'}>{isMember&&<Sidebar/>}<main className="site-main">{route.kind!=='landing'&&route.kind!=='media'&&route.kind!=='success'&&<div className="page-heading"><span className="eyebrow">{route.section}</span><h1>{route.title}</h1><p>{route.subtitle}</p></div>}{content}</main></div><footer><Logo/><p>One Family. One Mission. Transforming nations for Christ.</p><span>© 2026 Family House Connect</span></footer></div> }
