import type { AdminScreen, AdminScreenKind, Metric, Row } from './admin-routes.ts';

type Batch = 'J' | 'K' | 'L' | 'M' | 'N' | 'O';
type Nav = AdminScreen['nav'];

const metrics = (labels: string[], values = ['156', '78', '34', '63']): Metric[] => labels.map((label, index) => ({ label, value: values[index] ?? `${24 + index * 18}`, trend: index === 2 ? '+12.4%' : '+8.2%' }));
const peopleRows: Row[] = [
  { Name: 'Samuel David', Type: 'Author', Status: 'Active', Updated: 'May 31, 2024' },
  { Name: 'Mary Okoro', Type: 'Editor', Status: 'Active', Updated: 'May 30, 2024' },
  { Name: 'John Emeka', Type: 'Reviewer', Status: 'Active', Updated: 'May 29, 2024' },
  { Name: 'Grace Ese', Type: 'Contributor', Status: 'Active', Updated: 'May 27, 2024' },
  { Name: 'Daniel Adedeji', Type: 'Designer', Status: 'Pending', Updated: 'May 25, 2024' },
  { Name: 'Esther James', Type: 'Translator', Status: 'Active', Updated: 'May 22, 2024' },
];
const publicationRows: Row[] = [
  { Title: 'Walking in Dominion', Author: 'Samuel David', Category: 'Spiritual Growth', Format: 'Book', Status: 'Published', Published: 'May 17, 2024' },
  { Title: 'The Heart of Worship', Author: 'Mary Okoro', Category: 'Worship', Format: 'Book', Status: 'Published', Published: 'Apr 26, 2024' },
  { Title: 'Foundations of Faith', Author: 'John Emeka', Category: 'Doctrine', Format: 'Book', Status: 'Published', Published: 'Mar 27, 2024' },
  { Title: 'Living by the Spirit', Author: 'Grace Ese', Category: 'Christian Living', Format: 'Book', Status: 'Published', Published: 'Mar 20, 2024' },
  { Title: 'Kingdom Principles', Author: 'Daniel Adedeji', Category: 'Stewardship', Format: 'Book', Status: 'In Production', Published: '—' },
  { Title: 'Prayer That Prevails', Author: 'Mary Okoro', Category: 'Prayer', Format: 'Book', Status: 'Editorial Review', Published: '—' },
];
const financeRows: Row[] = [
  { Date: 'May 31, 2024', Donor: 'John Samuel', Category: 'Tithe', Channel: 'Credit Card', Amount: '₦50,000', Status: 'Success' },
  { Date: 'May 31, 2024', Donor: 'Grace Adeyemi', Category: 'Offering', Channel: 'Bank Transfer', Amount: '₦30,000', Status: 'Success' },
  { Date: 'May 31, 2024', Donor: 'David Johnson', Category: 'Missions', Channel: 'USSD', Amount: '₦100,000', Status: 'Success' },
  { Date: 'May 30, 2024', Donor: 'Faith Akin', Category: 'Projects', Channel: 'Debit Card', Amount: '₦25,000', Status: 'Success' },
  { Date: 'May 30, 2024', Donor: 'Mary Okoro', Category: 'Donations', Channel: 'Online', Amount: '₦20,000', Status: 'Success' },
  { Date: 'May 29, 2024', Donor: 'Anonymous', Category: 'Tithe', Channel: 'Bank Transfer', Amount: '₦15,000', Status: 'Pending' },
];
const communicationRows: Row[] = [
  { Message: 'Sunday Service Reminder', Channel: 'Email', Audience: '9,215', Status: 'Sending', Date: 'May 31, 2024' },
  { Message: 'Youth Conference Open', Channel: 'WhatsApp', Audience: '2,518', Status: 'Delivered', Date: 'May 30, 2024' },
  { Message: 'KCA Admissions Open', Channel: 'Email', Audience: '8,242', Status: 'Delivered', Date: 'May 29, 2024' },
  { Message: 'Missions Update', Channel: 'SMS', Audience: '3,600', Status: 'Scheduled', Date: 'May 27, 2024' },
  { Message: 'Prayer Request', Channel: 'Push', Audience: '1,624', Status: 'Delivered', Date: 'May 25, 2024' },
];
const securityRows: Row[] = [
  { 'Date & Time': 'May 31, 2024 10:43 AM', User: 'John Samuel', Module: 'People', Action: 'View', Status: 'Success', 'IP Address': '197.210.55.21' },
  { 'Date & Time': 'May 31, 2024 10:24 AM', User: 'Mary Okoro', Module: 'Finance', Action: 'Approve', Status: 'Success', 'IP Address': '197.210.11.14' },
  { 'Date & Time': 'May 31, 2024 10:03 AM', User: 'Grace Adeyemi', Module: 'KCA', Action: 'Update', Status: 'Failed', 'IP Address': '197.210.35.21' },
  { 'Date & Time': 'May 31, 2024 09:44 AM', User: 'Daniel David', Module: 'Users', Action: 'Delete', Status: 'Success', 'IP Address': '197.210.16.21' },
  { 'Date & Time': 'May 31, 2024 09:15 AM', User: 'Esther James', Module: 'Press', Action: 'Download', Status: 'Success', 'IP Address': '197.210.35.21' },
];

function route(batch: Batch, id: number, path: string, title: string, subtitle: string, kind: AdminScreenKind, nav: Nav, permission: string, extra: Partial<AdminScreen> = {}): AdminScreen {
  return { id: `${batch}-${String(id).padStart(2, '0')}`, batch, route: path, title, subtitle, kind, nav, permission, scope: 'assigned', ...extra };
}

export const pressScreens: AdminScreen[] = [
  route('J',1,'/admin/press','Press Dashboard','Overview of publishing operations and performance.','dashboard','press','press.dashboard.view',{metrics:metrics(['Publications','Manuscripts','In Production','Published'],['156','78','34','63']),items:['Walking in Dominion — 2,300','The Heart of Worship — 1,500','Foundations of Faith — 1,200','Living by the Spirit — 798']}),
  route('J',2,'/admin/press/publications','Publications','Manage all publications and their status.','table','publications','press.publication.view',{action:'+ Create Publication',columns:['Title','Author','Category','Format','Status','Published'],rows:publicationRows}),
  route('J',3,'/admin/press/publications/walking-in-dominion','Walking in Dominion','Hope to walk in authority and win daily.','detail','publications','press.publication.view',{tabs:['Overview','Details','Sales','Reviews','Assets','Translations','History'],details:{Author:'Samuel David',Category:'Spiritual Growth',Format:'Book (Paperback)',ISBN:'978-978-12345-6-7',Pages:'256',Language:'English',Published:'May 17, 2024',Price:'₦3,500',Status:'Published'},metrics:metrics(['Total Sold','Nigeria','Ghana','Kenya'],['12,842','7,221','1,842','1,356']),action:'Download PDF'}),
  route('J',4,'/admin/press/publications/create','Create Publication','Add a new publication to the system.','wizard','publications','press.publication.create',{tabs:['Basics','Content','Assets','Publishing'],action:'Next: Content',details:{Title:'',Subtitle:'',Author:'',Category:'',Format:'',Language:'',Description:'',Audience:''}}),
  route('J',5,'/admin/press/authors','Authors','Manage authors and their profiles.','table','authors','press.author.view',{action:'+ Add Author',columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('J',6,'/admin/press/authors/samuel-david','Samuel David','Author · Active','profile','authors','press.author.view',{tabs:['Overview','Books (12)','Bio','Awards','Documents','Activity'],details:{Email:'samuel.david@press.org',Phone:'+234 802 012 548',Location:'Lagos, Nigeria',About:'Author and apostle with a passion for equipping believers to walk in dominion.',Books:'12',Sales:'78,450',Downloads:'24,300'}}),
  route('J',7,'/admin/press/manuscripts','Manuscripts','Manage all manuscript submissions.','table','manuscripts','press.manuscript.view',{action:'+ Submit Manuscript',columns:['Title','Author','Submitted','Stage','Status'],rows:publicationRows.map((row,index)=>({Title:row.Title,Author:row.Author,Submitted:`May ${30-index}, 2024`,Stage:['Editorial Review','Theological Review','Copy Editing','Design Stage','ISBN Assignment','Approval'][index],Status:index<4?'In Review':'Pending'}))}),
  ...[
    ['Editorial Review','Review editorial structure, clarity and content.','editorial-review','Approve & Continue'],
    ['Theological Review','Ensure doctrinal accuracy and sound teaching.','theological-review','Approve & Continue'],
    ['Copy Editing','Review grammar, punctuation and consistency.','copy-editing','Approve & Continue'],
    ['Design Stage','Preview cover and interior layout.','design','Approve Design'],
    ['ISBN Assignment','Assign ISBN and publication details.','isbn','Save & Continue'],
    ['Publication Approval','Final approval before publication.','approval','Approve for Publication'],
  ].map((item,index)=>route('J',8+index,`/admin/press/manuscripts/power-of-covenant/${item[2]}`,item[0],item[1],index<3?'workflow':index===3?'detail':index===4?'form':'approval','manuscripts',`press.manuscript.${item[2]}.manage`,{action:item[3],tabs:['Editorial Review','Theological Review','Copy Editing','Design Stage','ISBN Assignment','Approval'],details:{Title:'The Power of Covenant',Author:'John Emeka',Assessment:'Good',Clarity:'Good',Consistency:'Good',Recommendation:'Proceed to the next stage'},items:['Overall Assessment — Excellent','Strengths — Well structured chapters','Comments — Good use of scriptures','Files — Edited Manuscript.docx']})),
  route('J',14,'/admin/press/distribution','Distribution','Manage distribution channels and inventory.','table','distribution','press.distribution.view',{action:'Add New Channel',columns:['Channel','Type','Status','Inventory'],rows:[{Channel:'Online Store',Type:'Digital',Status:'Active',Inventory:'1,250'},{Channel:'Bookstores',Type:'Retail',Status:'Active',Inventory:'850'},{Channel:'Churches',Type:'Direct',Status:'Active',Inventory:'2,300'},{Channel:'Events',Type:'Event',Status:'Active',Inventory:'500'}]}),
  route('J',15,'/admin/press/assets','Digital Assets','Manage digital files and resources.','operations','assets','press.asset.view',{tabs:['All Types','All Formats'],items:['Cover High Resolution — JPG, 1.8 MB','Interior PDF — PDF, 4.1 MB','eBook EPUB — EPUB, 1.4 MB','Promo Banner — PNG, 1.1 MB','Author Photos — JPG, 1.1 MB','Sample Chapter — PDF, 2.4 MB','Audiobook Sample — MP3, 3.6 MB','Anointed to Lead — PDF, 2.1 MB']}),
  route('J',16,'/admin/press/translations','Translation Queue','Manage translations in progress.','table','translations','press.translation.view',{columns:['Title','Language','Translator','Progress','Status'],rows:publicationRows.slice(0,5).map((row,index)=>({Title:row.Title,Language:['French','Hausa','Swahili','Portuguese','Amharic'][index],Translator:peopleRows[index].Name,Progress:`${80-index*15}%`,Status:index<3?'In Progress':'Not Started'}))}),
  route('J',17,'/admin/press/translations/walking-in-dominion/review','Translation Review','Manage editorial review and translation quality.','workflow','translations','press.translation.review',{action:'Approve Translation',tabs:['Translation','Review','Proofreading','Approval'],details:{Accuracy:'★★★★☆',Clarity:'★★★★★','Cultural Appropriateness':'★★★☆☆',Comments:'Good translation. Please correct the idiom in chapter 4.'}}),
  route('J',18,'/admin/press/catalogue','Catalogue','Browse all published works.','operations','publications','press.publication.view',{items:['Walking in Dominion — ₦3,500','The Heart of Worship — ₦2,000','Foundations of Faith — ₦2,500','Living by the Spirit — ₦3,000']}),
  route('J',19,'/admin/press/sales','Sales / Downloads','Track sales and download performance.','finance','press-sales','press.sales.view',{metrics:metrics(['Total Sales','Books Sold','Downloads','Avg Order Value'],['₦18,450,320','12,842','8,421','₦1,437']),items:['Walking in Dominion — ₦4,284,000','The Heart of Worship — ₦3,500,000','Foundations of Faith — ₦2,900,000','Living by the Spirit — ₦2,100,000']}),
  route('J',20,'/admin/press/analytics','Press Analytics','Comprehensive analytics and insights.','reports','press-analytics','press.analytics.view',{metrics:metrics(['Publications','Souls Reached','Sales','Revenue'],['63','12,842','4,256','₦6.3M']),items:['Online Store — 40%','Bookstores — 30%','Churches — 15%','Events — 10%','Partners — 5%']}),
];

export const financeScreens: AdminScreen[] = [
  route('K',1,'/admin/finance','Finance Dashboard','Overview of giving and financial performance.','dashboard','finance','finance.dashboard.view',{metrics:metrics(['Total Receipts','Total Transactions','Total Donors','Average Gift'],['₦48,930,250','3,862','2,145','₦12,680']),items:['Tithes — ₦19,520,000','Offerings — ₦11,324,500','Missions — ₦7,316,700','Projects — ₦4,854,000']}),
  route('K',2,'/admin/finance/transactions','Giving Transactions','Track all financial transactions.','table','finance-transactions','finance.transaction.view',{columns:['Date','Donor','Category','Channel','Amount','Status'],rows:financeRows}),
  route('K',3,'/admin/finance/transactions/trx-2024-0006487','Transaction Detail','TRX-2024-0006487 · Success','detail','finance-transactions','finance.transaction.view',{action:'Download Receipt',details:{Amount:'₦50,000.00',Type:'Tithe','Transaction ID':'TRX-2024-0006487',Date:'May 31, 2024 10:45 AM',Donor:'John Samuel',Email:'john.samuel@example.com',Phone:'+234 800 123 4567',Channel:'Credit Card (Visa)',Provider:'Paystack',Status:'Success'}}),
  ...[['Tithes','tithes','₦19,520,000'],['Offerings','offerings','₦12,245,500'],['Projects','projects','₦4,824,000'],['Donations','donations','₦3,146,550'],['Event Payments','event-payments','₦2,450,000'],['KCA Payments','kca-payments','₦5,680,000'],['Publication Payments','publication-payments','₦5,250,000']].map((item,index)=>route('K',4+index,`/admin/finance/${item[1]}`,item[0],`Manage ${item[0].toLowerCase()} and performance.`,'finance','finance-payments','finance.payment.view',{metrics:metrics([`Total ${item[0]}`,'Transactions','Average Gift'],[item[2],`${1452-index*71}`,`₦${index+7},488`]),rows:financeRows,columns:['Date','Donor','Category','Amount','Status']})),
  route('K',11,'/admin/finance/reconciliation','Reconciliation','Reconcile expected and received funds.','table','finance-reconciliation','finance.reconciliation.view',{action:'Reconcile',metrics:metrics(['Expected','Received','Difference'],['₦48,930,250','₦48,745,250','₦185,000']),columns:['Channel','Expected','Received','Variance','Status'],rows:[{Channel:'Bank Transfer',Expected:'₦18,250,000',Received:'₦18,245,000',Variance:'₦5,000',Status:'Matched'},{Channel:'USSD',Expected:'₦11,450,000',Received:'₦11,400,000',Variance:'₦50,000',Status:'Matched'},{Channel:'Card Payments',Expected:'₦12,200,000',Received:'₦12,150,000',Variance:'₦50,000',Status:'Unmatched'}]}),
  ...[['Receipts','receipts','Send Receipt'],['Refunds','refunds','Process Refund'],['Disputes','disputes','View all disputes'],['Payment Providers','providers','+ Add Provider'],['Financial Reports','reports','View All Reports'],['Finance Alerts','alerts','View All Alerts']].map((item,index)=>route('K',12+index,`/admin/finance/${item[1]}`,item[0],`Manage ${item[0].toLowerCase()}.`,index===3?'settings':index>=4?'reports':'table',index===4?'finance-reports':index===5?'finance-alerts':index===3?'finance-providers':'finance-transactions',`finance.${item[1]}.view`,{action:item[2],metrics:index<3?metrics(['Total','Pending','Completed'],['3,862','28','6']):undefined,columns:index<4?['Date','Donor','Reason','Amount','Status']:undefined,rows:index<4?financeRows:undefined,items:index>=4?['Income Statement — View','Giving Summary — Download','Fund Balances — View','Project Funding — Download','Donor Report — View']:undefined})),
];

const settings = [
  ['Platform Settings','platform','Configure global platform preferences and defaults.'],['Ministry Settings','ministry','Configure ministry types, structures and policies.'],['Church Settings','church','Configure church structure and global church options.'],['Home Church Rules','home-church-rules','Define rules and policies for Home Churches.'],['KCA Settings','kca','Configure Kingdom Citizens Academy preferences.'],['Mission Settings','mission','Configure mission and evangelism preferences.'],['Press Settings','press','Configure Kingdom Press preferences.'],['Event Settings','events','Configure global event preferences.'],['Payment Settings','payments','Configure payment gateways and financial preferences.'],['Notification Providers','notifications','Configure email, SMS, push and other providers.'],['Languages','languages','Manage supported platform languages.'],['Translation Governance','translation-governance','Manage translation workflow and responsibilities.'],['Feature Flags','feature-flags','Enable or disable platform features.'],['Maps Providers','maps','Configure Google Maps, Mapbox, or Leaflet — any one key activates maps.'],['Media Settings','media','Configure media storage and processing.'],['File / Upload Settings','uploads','Configure file upload rules and limits.'],['System Information','system-information','View platform system and server information.'],['AI API Configuration','ai-api','Configure AI services and API connections.'],['App Branding','branding','Upload the global logo and favicon used across admin, member, and public sites.'],
] as const;
export const settingsScreens: AdminScreen[] = settings.map((item,index)=>route('L',index+1,`/admin/settings/${item[1]}`,item[0],item[2],'settings','platform-settings',`settings.${item[1]}.manage`,{action:index===1?'+ Add Ministry Type':index===10?'+ Add Language':'Save Changes',tabs:['General','Configuration','Policies','Advanced'],details:{Name:item[0].replace(' Settings',''),Status:'Active',Timezone:'UTC+01:00 West Africa Time',Language:'English','Default Currency':'NGN','Auto Approval':'Enabled','Audit Logging':'Enabled'},items:['Primary Provider — Active','Secondary Provider — Active','Require Approval — Enabled','Retention Period — 730 days','Maximum File Size — 50 MB']}));

export const communicationScreens: AdminScreen[] = [
  route('M',1,'/admin/communications','Communications Dashboard','Overview of all ministry communications.','dashboard','communications','communications.dashboard.view',{metrics:metrics(['Messages Sent','Delivered','Opened','Clicked'],['128,450','112,342','68,540','12,845']),items:['Sunday Service Reminder — Delivered','KCA Admissions Open — Delivered','Youth Conference Invite — Delivered','Missions Update — Delivered']}),
  route('M',2,'/admin/communications/notifications','Notifications','System and communications notifications.','feed','communications','communications.notification.view',{tabs:['All','Unread','System','Campaigns'],rows:communicationRows.map(row=>({Item:row.Message,Detail:`${row.Channel} · ${row.Status}`,Time:row.Date}))}),
  route('M',3,'/admin/communications/broadcasts/create','Broadcast Composer','Compose and schedule a multichannel broadcast.','form','communications','communications.broadcast.create',{tabs:['Compose','Audience','Review','Schedule / Send'],action:'Next: Audience',details:{Channel:'Email',Campaign:'Sunday Service Reminder',Subject:'Join us this Sunday!',Message:'Hello {{first_name}}, join us for Sunday Service this weekend.'}}),
  route('M',4,'/admin/communications/audiences/create','Build Your Audience','Select people and filters to define your audience.','form','communications','communications.audience.create',{action:'Save Audience',metrics:metrics(['Total Audience','Email','SMS','WhatsApp'],['12,842','9,215','3,842','2,518']),details:{Country:'All Countries',Region:'All States',Church:'All Churches','Member Type':'All Types',Ministry:'All',Role:'All'}}),
  ...[['Create Announcement','announcements/create','Publish Now'],['Newsletter: May Update','newsletters/may-update','Next: Recipients'],['Send Email','email/create','Send Email'],['Send SMS','sms/create','Send SMS'],['Send WhatsApp Message','whatsapp/create','Send WhatsApp'],['Send Push Notification','push/create','Send Push'],['Create In-App Message','in-app/create','Publish Message']].map((item,index)=>route('M',5+index,`/admin/communications/${item[1]}`,item[0],`Compose and deliver ${item[0].toLowerCase()}.`,'form','communications',`communications.${item[1].split('/')[0]}.send`,{action:item[2],details:{Audience:index===0?'All Churches':'Newsletter Subscribers',Title:item[0],Subject:'Kingdom Update',Message:'Hello {{first_name}}, we are excited to share this important ministry update with you.',Schedule:'Send now'},items:['Recipients — 9,215','Estimated Open Rate — 48.6%','Credits Required — 3,842']})),
  route('M',12,'/admin/communications/templates','Templates','Manage reusable message templates.','table','templates','communications.template.view',{action:'+ New Template',columns:['Message','Channel','Audience','Status','Date'],rows:communicationRows}),
  route('M',13,'/admin/communications/delivery-queue','Delivery Queue','Messages scheduled or in progress.','table','communications','communications.delivery.view',{tabs:['All','Scheduled','Sending','Processing','Paused'],columns:['Message','Channel','Audience','Status','Date'],rows:communicationRows}),
  route('M',14,'/admin/communications/delivery-report','Delivery Report','Detailed delivery performance.','reports','communications','communications.delivery.view',{action:'Export',metrics:metrics(['Sent','Delivered','Opened','Clicked'],['9,215','8,845','4,356','1,145']),items:['Delivered — 8,845','Opened — 4,356','Clicked — 1,145','Bounced — 248']}),
  route('M',15,'/admin/communications/failed','Failed Messages','Messages that were not delivered.','table','communications','communications.delivery.manage',{columns:['Message','Channel','Audience','Status','Date'],rows:communicationRows.map(row=>({...row,Status:'Failed'}))}),
  route('M',16,'/admin/communications/settings','Communication Settings','Configure global communication preferences.','settings','communications','communications.settings.manage',{action:'Save Changes',tabs:['Channels','Email Settings','SMS Settings','WhatsApp Settings','Push Settings'],details:{'From Name':'Kingdom Platform','From Email':'noreply@kingdomplatform.org','Reply To':'support@kingdomplatform.org','Track Opens':'Enabled','Track Clicks':'Enabled','Bounce Handling':'Hard bounces'}}),
];

const analyticsNames = [['Global Reports',''],['Church Analytics','churches'],['Home Church Analytics','home-churches'],['Membership Analytics','membership'],['First-Timer Conversion','first-timers'],['Evangelism Analytics','evangelism'],['Mission Analytics','missions'],['KCA Analytics','kca'],['Mentor Effectiveness','mentors'],['Press Analytics','press'],['Finance Analytics','finance'],['Country Comparison','countries'],['Territory Comparison','territories'],['Trends','trends'],['Pastoral AI','pastoral-ai'],['Press AI','press-ai']] as const;
export const analyticsScreens: AdminScreen[] = analyticsNames.map((item,index)=>route('N',index+1,`/admin/reports${item[1]?`/${item[1]}`:''}`,item[0],index<14?'Comprehensive performance analytics and insights.':'AI-assisted ministry insights.','reports',index>=14?'report-ai':'reports',`reports.${item[1]||'global'}.view`,{metrics:metrics(index===0?['Total People','Active Churches','Home Churches','Countries']:['Total','Active','New','Growth'],index===0?['128,450','1,842','3,256','78']:undefined),items:index>=14?['People Insights — View Alerts','KCA Insights — View Unit','Performance AI — Ask AI','Content AI — View Details']:['Nigeria — 32,450','Ghana — 16,872','Kenya — 11,364','United Kingdom — 5,245','Canada — 3,245']}));

export const securityScreens: AdminScreen[] = [
  route('O',1,'/admin/security','Security Dashboard','Monitor access, alerts and platform risk.','dashboard','security','security.dashboard.view',{metrics:metrics(['User Accounts','Active Users','Failed Logins','Security Alerts'],['12,842','3,256','1,248','24']),items:['Impossible travel — 18','Multiple failed logins — 124','Unusual login location — 36','Privilege escalation — 9']}),
  route('O',2,'/admin/security/audit-logs','Audit Logs','Review all platform audit events.','table','audit','security.audit.view',{columns:['Date & Time','User','Module','Action','Status','IP Address'],rows:securityRows}),
  route('O',3,'/admin/security/audit-logs/audit-2024-000314','Audit Detail','May 31, 2024 10:43 AM','detail','audit','security.audit.view',{action:'Download',details:{User:'John Samuel','User Role':'People Manager',Module:'People',Action:'View',Resource:'Person Profile','IP Address':'197.210.55.21',Location:'Lagos, Nigeria',Device:'Windows 10 / Chrome 124',Status:'Success'}}),
  route('O',4,'/admin/security/login-history','Login History','Review successful and failed sign-ins.','table','security','security.login.view',{columns:['Date & Time','User','Status','IP Address','Location','Device'],rows:securityRows.map(row=>({'Date & Time':row['Date & Time'],User:row.User,Status:row.Status,'IP Address':row['IP Address'],Location:'Lagos, Nigeria',Device:'Windows / Chrome'}))}),
  route('O',5,'/admin/security/access-decisions','Access Decisions','Review authorization decisions across the platform.','table','security','security.decision.view',{columns:['User','Module','Action','Status','Date'],rows:securityRows.map(row=>({User:row.User,Module:row.Module,Action:row.Action,Status:row.Status,Date:row['Date & Time']}))}),
  route('O',6,'/admin/security/alerts','Security Alerts','Monitor security events requiring action.','feed','security','security.alert.view',{tabs:['All','High','Medium','Low'],rows:['Impossible travel detected','Multiple failed login attempts','Unusual data export','New device sign-in','Privilege escalation attempt'].map((Item,index)=>({Item,Detail:['High','Medium','High','Low','High'][index],Time:'Now'}))}),
  route('O',7,'/admin/security/data-classification','Data Classification','Define and enforce information classifications.','table','security','security.classification.manage',{action:'+ New Classification',columns:['Name','Type','Status','Updated'],rows:[{Name:'Public',Type:'Everyone',Status:'Active',Updated:'May 31, 2024'},{Name:'Internal',Type:'All Staff',Status:'Active',Updated:'May 30, 2024'},{Name:'Confidential',Type:'Role Based',Status:'Active',Updated:'May 29, 2024'},{Name:'Restricted',Type:'Need to Know',Status:'Active',Updated:'May 28, 2024'}]}),
  route('O',8,'/admin/security/safeguarding','Safeguarding Dashboard','Monitor safeguarding cases and restricted records.','reports','safeguarding','safeguarding.dashboard.view',{metrics:metrics(['Open Cases','Under Review','High Priority','Closed Cases'],['24','8','6','18']),items:['Report — 10','Concern — 6','Disclosure — 5','Other — 3']}),
  route('O',9,'/admin/security/safeguarding/cases','Safeguarding Cases','Manage restricted safeguarding cases.','table','safeguarding','safeguarding.case.view',{columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('O',10,'/admin/security/safeguarding/cases/case-0032','CASE-0032','High Priority · Open','restricted','safeguarding','safeguarding.case.view_restricted',{tabs:['Overview','Timeline','People','Notes','Documents','Actions'],details:{Type:'Report','Date Reported':'May 31, 2024',ReportedBy:'Mary Okoro',AssignedTo:'Sarah Okoro',Location:'Lagos, Nigeria',Description:'Reported inappropriate behaviour during a youth meeting.'},items:['Add Note','Assign Case','Upload Document','Change Priority','Close Case']}),
  route('O',11,'/admin/security/child-profiles','Child Profiles','Restricted profiles for minors.','table','safeguarding','safeguarding.child.view',{action:'+ Add Child',columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('O',12,'/admin/security/guardian-consent','Guardian Consent','Manage pending parental and guardian consent.','table','safeguarding','safeguarding.consent.view',{columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('O',13,'/admin/security/communication-restrictions','Communication Restrictions','Control communication restrictions and scope.','table','security','security.restriction.manage',{action:'+ New Restriction',columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('O',14,'/admin/security/pastoral-records','Pastoral Records','Restricted pastoral and counselling records.','restricted','security','pastoral.record.view_restricted',{columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('O',15,'/admin/security/restricted-access','Restricted Record Access','Audit every access to restricted records.','table','security','security.restricted_access.view',{columns:['Date & Time','User','Module','Action','Status','IP Address'],rows:securityRows}),
  route('O',16,'/admin/security/data-export-requests','Data Export Requests','Review and approve data export requests.','table','privacy','privacy.export.view',{action:'+ New Request',columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('O',17,'/admin/security/data-deletion-requests','Data Deletion Requests','Review privacy deletion requests.','table','privacy','privacy.deletion.view',{columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('O',18,'/admin/security/privacy-requests','Privacy Requests','Manage all data-subject privacy requests.','table','privacy','privacy.request.view',{columns:['Name','Type','Status','Updated'],rows:peopleRows}),
  route('O',19,'/admin/security/configuration','Security Configuration','Configure authentication and protection.','settings','security','security.settings.manage',{action:'Save Changes',tabs:['Authentication','Password Policy','MFA Settings','Session Settings','IP Allowlist','Data Protection'],details:{'MFA for Admins':'Enabled','Session Timeout':'30 minutes','Password Expiry':'90 days','Failed Login Lockout':'5 attempts','Encryption':'Enabled','IP Allowlist':'Enabled'}}),
];

export const platformScreens: AdminScreen[] = [...pressScreens,...financeScreens,...settingsScreens,...communicationScreens,...analyticsScreens,...securityScreens];
